### ISSUE TITLE
Clearvars argn, Cleartags argn, Clearctags argn Not Working

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source-experimental#281]
for example;

VAR0.Spawn_1=1 does not clear variable Serv.Clearvars Spawn_

Src.tag0.Vendor_1=1 does not clear variable Src.ClearTags Vendor_

Src.ctag0.Deed_1=1 does not clear variable Src.ClearcTags Deed_

And 

Not working custom array function

[FUNCTION ARRAY]
LOCAL.TEMP = <ARGV[<EVAL <ARGV> - 1>]> -1
RETURN <ARGV[<DLOCAL.TEMP>]>

**Comment by cbnolok** [comment]
That array function looks incomplete to me, this <ARGV[<EVAL - 1>]> wouldn't work

**Comment by canavar2212** [comment]
Hello,
This series separation function works smoothly in normal 56d version. How do you think the array separation function should be?
Thank you.

**Comment by canavar2212** [comment]
Then errors that occur after the change (this change);

ERROR:(sphere_chardef_monsters.scp,11508)Tanimsiz anahtar: 'TAG.Barding.Diff'
ERROR:(sphere_chardef_monsters.scp,11509)Tanimsiz anahtar: 'TAG.SlayerGroup'
ERROR:(sphere_chardef_monsters.scp,12398)Tanimsiz anahtar: 'TAG.Barding.Diff'
ERROR:(sphere_chardef_monsters.scp,12399)Tanimsiz anahtar: 'TAG.SlayerGroup'
ERROR:(sphere_chardef_monsters.scp,10483)Tanimsiz anahtar: 'TAG.Barding.Diff'
ERROR:(sphere_chardef_monsters.scp,10485)Tanimsiz anahtar: 'TAG.SlayerGroup'
ERROR:(sphere_chardef_monsters.scp,8397)Tanimsiz anahtar: 'Tag.Barding.Diff'
ERROR:(sphere_chardef_monsters.scp,8398)Tanimsiz anahtar: 'Tag.Slayergroup'

**Comment by cbnolok** [comment]
That should be fixed now. About the function, what should that do in particular?

**Comment by canavar2212** [comment]
Chardef error solved but itemdef error still in progress...

ERROR:(sphere_item_provisions_ore.scp,447)Undefined symbol '' ['color_o_iron']
ERROR:(sphere_item_resources.scp,1038)Undefined symbol '' ['color_o_granite']
ERROR:(sphere_item_resources.scp,1052)Undefined symbol '' ['color_o_marble']
ERROR:(sphere_item_resources.scp,1066)Undefined symbol '' ['color_o_sandstone']

**Comment by canavar2212** [comment]
problem; the value is zero.
COLOR_O_IRON          00 //OPTION: 0763
COLOR_O_GRANITE     0   //0B8E
COLOR_O_MARBLE      0  //0B8B,0B8C 
COLOR_O_SANDSTONE   0

**Comment by cbnolok** [comment]
```
ERROR:(sphere_item_provisions_ore.scp,447)Undefined symbol '' ['color_o_iron']
ERROR:(sphere_item_resources.scp,1038)Undefined symbol '' ['color_o_granite']
ERROR:(sphere_item_resources.scp,1052)Undefined symbol '' ['color_o_marble']
ERROR:(sphere_item_resources.scp,1066)Undefined symbol '' ['color_o_sandstone']
```
What's at that lines? I tried to replicate that but had no luck

**Comment by canavar2212** [comment]
`[ITEMDEF 01BEF]
DEFNAME=I_INGOT_IRON
TYPE=T_INGOT
RESOURCES=I_ORE_IRON
SKILLMAKE=20.0 MINING
NAME=Iron Ingot%s
TDATA1=20.0
TDATA2=50.0
WEIGHT=2
RESDISPDNHUE=color_o_iron`

**Comment by cbnolok** [comment]
It should be working
